In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


$G_(x) = x > a $

In [2]:
X = np.arange(6)
y = np.array([1, 1, -1, -1, 1, -1])
cut_list = [0.5, 1.5, 2.5, 3.5, 4.5]

In [8]:
class my_adaboost():
    def __init__(self):
        pass
    def G_x_vertor(self, a):
        y_pred = []
        #某个切分点对应的loss值
        for x in self.X:
            if x < a:
                y_pred.append(1)
            else:
                y_pred.append(-1)
        
        return np.array(y_pred)
    
    def G_x(self, x, a):
        if x > a:
            return -1
        else:
            return 1
    
    def fit(self, X, y, epochs = 3):
        self.X = X
        self.y = y
        self.N = len(X)
        self.w = np.array([1/self.N]*self.N)
        self.alpha = np.zeros(epochs)
        self.a = np.zeros(epochs)
        for i in range(epochs):
            print("第"+ str(i) + "轮")
            print("w:")
            print(self.w)
            self.alpha[i], self.a[i] = self.update()
            print("\n\n\n")
           
            
    def predict(self, X):
        '''传入的X为array'''
        y_pred = []
        for x in X:
            res = 0
            for i in range(len(self.a)):
                res += self.alpha[i]*self.G_x(x, self.a[i])
            y_pred.append(G_x(x, a))
        return np.array(y_pred)
            
        
    def update(self):
        loss_list = []
        for cut_point in cut_list:
            y_pred = self.G_x_vertor(cut_point)
            mask = y_pred != self.y #获取预测不对的数据的索引
        
            #print(mask)
            #print(self.w[mask])
            loss = sum(self.w[mask])
            #print(mask)
            loss_list.append(loss)
        
        loss_array = np.array(loss_list)
        print("loss:")
        print(loss_array)
        print()
        min_loss = np.min(loss_array)
        min_loss_index = np.argmin(loss_array)
        
        alpha = 1/2 * np.log(1/min_loss - 1)
        #print(self.w)
        #更新w
        temp_array = -alpha * self.y * self.G_x_vertor(cut_list[min_loss_index])
        Zm = np.dot(self.w , np.exp(temp_array))
        #print("y_predcit")
        #print(self.G_x_vertor(min_loss_index))
        #print(temp_array)
        #print("Zm" + str(Zm))
        self.w = self.w / Zm * np.exp(temp_array)
        return alpha, cut_list[min_loss_index]
    

In [9]:
clf = my_adaboost()
clf.fit(X, y)

第0轮
w:
[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
loss:
[0.33333333 0.16666667 0.33333333 0.5        0.33333333]





第1轮
w:
[0.1 0.1 0.1 0.1 0.5 0.1]
loss:
[0.6 0.5 0.6 0.7 0.2]





第2轮
w:
[0.0625 0.0625 0.25   0.25   0.3125 0.0625]
loss:
[0.375  0.3125 0.5625 0.8125 0.5   ]







In [10]:
clf.alpha

array([0.80471896, 0.69314718, 0.39422868])

In [ ]:
clf.a

$G(x) = 0.80471896G_1(x)+ 0.69314718G_2(x) +  0.39422868G_3(x)$