In [2]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


# 向量的基本性质

In [3]:
# 向量
a = np.array([1, 2])
b = np.array([3, 4])

In [4]:
#加法
a + b

array([4, 6])

In [5]:
#数乘
2 * a

array([2, 4])

## 点积
- 定义：接受实数R上的两个向量A，B，输出一个实数
- 意义：向量A，B的模乘以夹角余弦 $$ A \cdot B = |A||B|\cos{\theta} $$

In [15]:
a = np.array([2, 2])
b = np.array([2, -2])
#內积
np.inner(a, b) #1*3 + 2*4

0

In [18]:
#根据夹角余弦计算內积

# np.linalg.norm(a) = sqrt(2^2 + 2^2)
np.linalg.norm(a) * np.linalg.norm(b) * np.cos(np.pi/2)

4.898587196589414e-16

### 点积作用
- 计算夹角
- 求向量分量：向量在某一方向上的分量等于该向量与这一方向上的单位向量的点积

In [28]:
# 计算夹角
a = np.array([-1, 1, 0])
b = np.array([-1, 0, 2])
cosx = np.inner(a, b)/(np.linalg.norm(a)*np.linalg.norm(b))
#np.arccos()输出弧度，转换成度数
np.arccos(cosx)/np.pi*180

71.56505117707799

In [29]:
#求向量分量
#a在x轴上的分向量
ex = np.array([1, 0, 0])
np.inner(a, ex)

-1

## 叉积
- 定义
A = $\begin{bmatrix}
a_1 \\ 
a_2
\end{bmatrix}$

B = $\begin{bmatrix}
b_1 \\ 
b_2
\end{bmatrix}$

$A \times B =$
$\begin{bmatrix}
a_1 & b_1\\ 
a_2 & b_2
\end{bmatrix}$ = $a_1b_2 - a_2b_1$
- 意义：平行四边形面积

### 叉积作用
- 计算面积    
$ \frac{1}{2} |A|\times|B| $
 
- 体积    
$ A\cdot (B \times C)  $ 
 
- 判断共面: 向量A， B， C构成的平行六面体的体积是否为0，为0则共面
 
- 计算法向量 
$ N = A \times C $

In [34]:
#求p1(-1, 0, 1), p2(0, 2, 2), p3(0, -1, 2)三点围成的三角形面积
p1 = np.array([-1, 0, 1])
p2 = np.array([0, 2, 2])
p3 = np.array([0, -1, 2])
A = p1 - p2
B = p1 - p3
#面积
1/2 * np.linalg.norm(np.cross(A, B))

2.1213203435596424

In [39]:
#求p1(-1, 0, 1), p2(0, 2, 2), p3(0, -1, 2), p4(0, 0, 0)四点围成的四面体的体积
p1 = np.array([-1, 0, 1])
p2 = np.array([0, 2, 2])
p3 = np.array([0, -1, 2])
p4 = np.array([0 ,0, 0])
A = p1 - p2
B = p1 - p3
C = p1 - p4
B_times_C = np.cross(B, C)
np.abs(1/3 * np.inner(A, B_times_C))

2.0

In [40]:
#求p1(-1, 0, 1), p2(0, 2, 2), p3(0, -1, 2)三点构成平面的法向量
p1 = np.array([-1, 0, 1])
p2 = np.array([0, 2, 2])
p3 = np.array([0, -1, 2])
A = p1 - p2
B = p1 - p3

np.cross(A, B)

array([ 3,  0, -3])

# 行列式

####  行列式的意义
   行列式通常和方程组联系起来
   
   - det(I) != 0,则方程有唯一解 
   
   - det(I) = 0,则方程没有唯一解

In [43]:
#计算行列式
A = np.arange(1, 5).reshape(2, 2)
np.linalg.det(A)

-2.0000000000000004