In [1]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


# 矩阵运算

点击查看 [np.array 和 np.mat 的区别](https://blog.csdn.net/vincentlipan/article/details/20717163)

In [4]:
A = np.arange(1, 5).reshape(2, 2)
'''
array([[1, 2],
       [3, 4]])
'''
B = np.arange(6, 10).reshape(2, 2)
'''
array([[6, 7],
       [8, 9]])
'''
#加法
A + B

array([[ 7,  9],
       [11, 13]])

In [11]:
#数乘
print(A * 2))
print(np.multiply(A, 2))

[[2 4]
 [6 8]]
[[2 4]
 [6 8]]


In [12]:
#乘法
np.dot(A, B)

array([[22, 25],
       [50, 57]])

In [14]:
#加法
print(A + B)
print(A - B)

print(np.add(A, B))
print(np.subtract(A, B))

[[ 7  9]
 [11 13]]
[[-5 -5]
 [-5 -5]]
[[ 7  9]
 [11 13]]
[[-5 -5]
 [-5 -5]]


In [16]:
#转置
print(np.transpose(A))
print(A.T)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


# 特殊矩阵